services:

  # FastAPI app
  web:
    build: .
    command: bash -c  'alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload'
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - db

  # PostgreSQL
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'

#  db_test:
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER_TEST}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_TEST}
#      - POSTGRES_DB=${POSTGRES_DB_TEST}
#    ports:
#      - '5433:5432'


  # PostgreSQL UI
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db