"""extended fields name and surname for user with non-nullable

Revision ID: a31a81f806e6
Revises: e89e8b2ee045
Create Date: 2023-10-22 15:43:47.718249

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a31a81f806e6'
down_revision: Union[str, None] = 'e89e8b2ee045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
